name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        release: [stable, nightly]
        os: [ubuntu-latest]
    env:
      CI: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.release }}

      - name: Install Dependencies
        run: |
          git config --global core.compression 0
          git clone https://github.com/nvim-lua/plenary.nvim tmp/plenary
          git clone https://github.com/nvim-telescope/telescope.nvim tmp/telescope

      - name: E2E Test
        run: |
          bundle exec rspec

      - name: Unit Test
        run: |
          make test
